changelog:
  exclude:
    labels:
      - ignore-for-release
      - invalid
      - Blocked
    authors:
      - dependabot
  categories:
    - title: ":boom: Breaking Change"
      labels:
        - "PR: Breaking Change :boom:"
    - title: ":rocket: New Feature"
      labels:
        - "PR: New Feature :tada:"
    - title: ":bug: Bug Fix"
      labels:
        - "PR: Bug Fix :bug:"
    - title: ":memo: Documentation"
      labels:
        - "PR: Docs :memo:"
    - title: Other Changes
      labels:
        - "*"
