name: docs
on:
  push:
    branches:
      - next
    paths:
      - "website/**"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy Docs
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          install_website: true
      - name: Build 🔧
        run: yarn docs-build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: "React Native Elements CI"
          user_email: "react-native-elements-ci@users.noreply.github.com"
          cname: reactnativeelements.com
